---
- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    ios_banner:
      banner: login
      text: |
        tavo tavito
      state: present

  - name: Merge provided configuration with device configuration
    ios_interfaces:
      config:
        - name: GigabitEthernet2
          description: Configured and Merged by Ansible Network
          enabled: true

